### PR TITLE
Add autocomplete search via DocSearch project

### PR DESCRIPTION
**Pull request by dzello**
This PR adds search to the webpack documentation based on the [DocSearch](https://community.algolia.com/docsearch/) project. The search index is updated by Algolia automatically every 24 hours. The configuration for the indexing process lives in [docsearch-configs/configs/webpack.json](https://github.com/algolia/docsearch-configs/blob/master/configs/webpack.json).

Here's a screenshot of the search box and the results overlay.

Searching webpack docs

### CODE REVIEW

**Comment by bebraw** [comment]
@TheLarkInn Any thoughts on this? Looks like a good addition to the site.

**Comment by dzello** [comment]
Here's a link to a [live version](http://dzello.com/docs/) so you can see it in action.

**Comment by dzello** [comment]
I saw your note on the [new docs repo](https://github.com/webpack/webpack.js.org/issues/184#issuecomment-248814278), @SpaceK33z. What do you think about this PR for the current docs? The idea is that we could start learning about query patterns to optimize the search relevance for the new site. (I'll be happy to share all the data from the Algolia side).

**Comment by SpaceK33z** [comment]
Looks very good @dzello.

I personally don't like serving things from a CDN except when used with an `integrity` attribute, but I don't know how the rest thinks of that?

**Comment by dzello** [comment]
Good idea to add that attribute @SpaceK33z, will add a commit for that soon.

**Comment by dzello** [comment]
Commit for SRI added, fixed to version 2.1.8. Does this look good?

**Comment by SpaceK33z** [comment]
Very nice @dzello. It looks good to me. @TheLarkInn, maybe you can also review this & merge if you're fine with it?

**Comment by TheLarkInn** [comment]
This looks fine from what I can tell. I'm not _crazy_ about slapping minified source code that we have more vetted first, but I suppose we can not review that source. Otherwise this looks good to me.

**Comment by dzello** [comment]
@TheLarkInn The source is something you can review actually, and totally understand wanting to be cautious. Here are links to the [un-minified CSS source](http://cdn.jsdelivr.net/docsearch.js/2.1.8/docsearch.css) and [un-minified JS](http://cdn.jsdelivr.net/docsearch.js/2.1.8/docsearch.js), and the original source for those comes from [algolia/docsearch](https://github.com/algolia/docsearch).

**Comment by TheLarkInn** [comment]
This looks good to me. Thanks for the clarification.

**Comment by TheLarkInn** [comment]
Thank you.

**Comment by SpaceK33z** [comment]
Oh yeah! Thanks again @dzello, if only I had this when learning webpack haha.

**Comment by dzello** [comment]
Awesome! 😀  Anything I/we need to do to deploy it?

@SpaceK33z Yeah! It should make the search-learn loop faster for new users, a lot faster than jumping back and forth between the docs and Google anyway :)

**Comment by dzello** [comment]
Small ping here for someone to deploy the changes, so we don't forget :)

**Pull request merged**
