### PR TITLE
Add deprecation warning to the old webpack doc site

### PR DESCRIPTION
**Pull request by dmitriid**
@TheLarkInn

### CODE REVIEW

**Comment by dmitriid** [comment]
This is what it looks like

**Review by SpaceK33z — APPROVED** [review]

**Comment by SpaceK33z** [comment]
Thanks!

**Comment by dmitriid** [comment]
@SpaceK33z np

I couldn't wrap my head around new website's structure (yet?), it would be nice to add a [Typescript](http://www.typescriptlang.org)-like bar at the top announcing webpack 2 and some relevant links (to the migration guide etc.)

I wonder if I should add a feature request there...

**Comment by dmitriid** [comment]
@SpaceK33z 

Also, the warning doesn't show up on the landing page. It looks like it's generated from some other code?

**Comment by dmitriid** [comment]
I think it's this one, I may be wrong: https://github.com/webpack/webpack.github.com/pull/13

**Pull request merged**
