### PR TITLE
needs double quotes to run with no errors

### PR DESCRIPTION
**Pull request by ArgTang**
I Am following the tutoria,l and had to google for help. When running command with single quotes i get an error:

Error in ./style.css
Module parse failed ....
You may need an appropriate loader to handle this file type.
...

May be related to webpack issue #1130 https://github.com/webpack/webpack/issues/1130

### CODE REVIEW

**Comment by shama** [comment]
Thanks!

**Comment by aguegu** [comment]
In my current try, single quotes works, while double quotes not.

screen shot 2015-11-27 at 17 04 15

**Comment by shama** [comment]
@aguegu I ended up just adding a note to make people aware in some environments it could require double quotes while others require single quotes: bf99436f98b287e3316d6e0b7de57c2a9e97cc97

**Comment by aguegu** [comment]
yep, thx. maybe it is just how it works ... 

Thanks to this issue, otherwise, it may drive me crazy.

**Pull request merged**
